language: node_js
cache:
  directories:
  - node_modules
env:
  - REACT_APP_SPREADSHEET=1fsQHaT2ZG1uRKmuHagoUjReNMpFH3_fSGw9HLLcphIg REACT_APP_CLIENT_ID=826952396520-1kpdq0jbso689jldpfou2v7mevjf5u1h.apps.googleusercontent.com
  secure: klh3Bt7zaAbkzaayeMYDKAM2w6DozaXFikarLuvoxbriVzHWifrRQOZ6zX+zt9faKw8v5afH33t/p3UciT6TrMUnl5fkxAENnkR5TlsyXaaQCCMUdumeF+UxLoLxilgDsy7y/TH1h1mHkVDk6UUHRyQPy7rV9upZrcXfmMSBPuXe9ITwPgi9L0xZ5tZrxpD8QsGfxI6sm2ztsLT28U+TXGsRvdlg5IZYx4/h+ohdl0tdN8BKFbn6TzQ7mcW4CgPa/RmpEqWjf9UaIzARr6S3FkgpVydoTRu43PEizb3iVVNpaLMg+NimMAThWYbMabFRwOLlYrg9WxjLiSDp6u7Jscfg7X9+gugZ2CoABecR4WnfeYnxdV+bavYUAtvfT2FygPfI7ld/959LrWVXw1p+Spj2IdAD9Bsel2oVenvsh5PYWeCaiyQJgsTwy4cekOWRCep+GzDvaSs/9+dghB3/mgwJxPfkvvbJ7WHEPHpHApQfcoV38v78EfSGTlBuQUK3PdZU82A1h3LAHizZWPX7aozK/gcUm9UTEQ0zQdnVNajqwLCoFweOQp1nXX1o5GSxcF2QyvBFufUJyztKYoAx+r3lFywVYVBvRIiRnyIdd6zGvwxGyZQuumlz+93xVBFIzEitNNlyRkp5WN/+BF14pGVzgK1iu3/PNwwGFvZmiAhQ=
script:
  - yarn run build
deploy:
  provider: s3
  access_key_id: AKIAJ6JLQ6HT2QG2BEYQ
  secret_access_key:
    secure: hJCst+QmokwB5yRrYY58YtxwBX+bdI67rQIW98HrfUL34fnMBL2Od2twR7JbWvtPJPz9zwANphssHq1rnzhApOHNGA31whtzJvQb4oqlq9yGQsDIY9QWHtzHUiG4UCqzVPCl77tEzVb/yUavkMdwwPRiwCvAdcTmMYOU9mhjcPq8FZ/AmZDsWlAbkxAMuLAl8gcWGPHdV94IlUl1nabhKkrVtBIfurXqc8CpigIe4iBC8U+xrAjR+FSN8CJrKj/lBZtKRC5FsoGySNyEOMgyhrywmG8gJxadX2bKQq8flf8UedjXiOfeTcxJ/ftXhaJgkwPCvUJ4smXRnGkOP8ATd9oOG56ptDHb0weIebKTrELq1t7mmVdt60ndjfxHMbUyq/mbQRhiAUhEvLrsfOTLc6KwFqv+hSQW+nf4EnOasQK80/g3SQEc2nBNDZv0e5ks5OMxuEUwZ956GEekkDFGaRQtOUHyde2W5iDUi5M9iSwq2yyRQphdNJzHJbbu07AFmKMREyDaO8tDPg8tzTNcuCUC6SQ4D9utTWZ8OCe6ziaow2b2xZ+q9mCECRojWPTozqCwKYGwudg3GG0+WiuoofTrlLnTg45mPPfdolZ+ZaYlQcQwiNiqcrZYorHcxZnUthDPKXnb1sh3du/HZ04wK43tTVRCGXAUuS2HoTTKAuM=
  bucket: fika.resync.games
  local-dir: build
  acl: public_read
  on:
    repo: kadhirvelm/fika
