version: 2
jobs:
  build_test:
    docker:
      - image: circleci/node:7.10
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name: Install
          command: yarn install
      - run: 
          name: Lint
          command: yarn lint
      # - run: 
      #     name: Test
      #     command: CI=true yarn test
      - run: 
          name: Build
          command: yarn build
  install:
    docker:
      - image: circleci/node:7.10
    steps:
      - add_ssh_keys
      - checkout
      - restore_cache:
          name: Restore yarn package cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          name: Save yarn package cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  deploy:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
        name: Building
        command: yarn build
      - run:
        name: Deploying
        command: aws s3 sync build/ s3://atlasp --delete --region us-west-1
workflows:
  version: 2
  build_and_test:
    jobs:
      - install
      - build_test:
          requires:
            - install
      - deploy:
          requires:
            - build_test
          filters:
            branches:
              only:
                - master
